"""
schedulo/export_engine/docx_renderer.py
python-docx DOCX renderer for Schedulo timetables.

Produces a Word document with one table per section,
styled with:
  - Colour-shaded cells matching slot types
  - Bold headers (days/periods)
  - Section heading style
  - Professional university timetable layout
"""

from __future__ import annotations

import io
import logging
from datetime import datetime
from typing import Any

import pandas as pd

logger = logging.getLogger(__name__)

# ── DOCX OXml colour codes ─────────────────────────────────────────
TYPE_COLOUR_DOCX = {
    "Theory":   "DCE6F1",
    "Lab":      "D9EAD3",
    "Lab_Cont": "BDD7EE",
    "Lunch":    "FFEB9C",
    "Free":     "EEECE1",
    "Project":  "E2EFDA",
}
HEADER_COLOUR_DOCX = "4472C4"


class DOCXRenderer:
    """
    Renders Schedulo timetables to a DOCX file using python-docx.

    Usage:
        renderer = DOCXRenderer()
        buf = renderer.render_from_dataframes(section_dfs, department="CSE")
        with open("timetable.docx", "wb") as f:
            f.write(buf.read())
    """

    def render_from_dataframes(
        self,
        section_dfs: dict[str, pd.DataFrame],
        department: str = "University Timetable",
        academic_year: str = "2024-25",
    ) -> io.BytesIO:
        """
        Render all sections to a single DOCX document.

        Args:
            section_dfs: {section_id → DataFrame(rows=Days, cols=Periods)}

        Returns:
            BytesIO containing the .docx bytes
        """
        try:
            from docx import Document
            from docx.shared import Pt, RGBColor, Cm, Inches
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            from docx.enum.table import WD_TABLE_ALIGNMENT, WD_ALIGN_VERTICAL
            from docx.oxml.ns import qn
            from docx.oxml import OxmlElement
        except ImportError:
            logger.warning("python-docx not installed — returning empty DOCX stub")
            return io.BytesIO(b"PK\x03\x04")  # minimal ZIP stub

        doc = Document()

        # ── Document title page ────────────────────────────────────
        title = doc.add_heading("University Timetable", 0)
        title.alignment = 1  # WD_ALIGN_PARAGRAPH.CENTER
        sub = doc.add_paragraph(f"{department}  |  Academic Year: {academic_year}")
        sub.alignment = 1
        sub.runs[0].font.color.rgb = RGBColor(0x44, 0x72, 0xC4)

        gen_time = doc.add_paragraph(
            f"Generated by Schedulo  •  {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
        )
        gen_time.alignment = 1
        gen_time.runs[0].font.size = Pt(9)
        gen_time.runs[0].font.color.rgb = RGBColor(0x99, 0x99, 0x99)
        doc.add_page_break()

        for section_id, df in section_dfs.items():
            logger.info(f"DOCXRenderer: rendering section {section_id}")

            # Section heading
            sec_heading = doc.add_heading(f"Section: {section_id}", level=1)
            sec_heading.runs[0].font.color.rgb = RGBColor(0x44, 0x72, 0xC4)

            days = list(df.index)
            periods = list(df.columns)

            # Create table: rows = days + 1 header, cols = periods + 1 day label
            table = doc.add_table(rows=len(days) + 1, cols=len(periods) + 1)
            table.style = "Table Grid"
            table.alignment = WD_TABLE_ALIGNMENT.CENTER

            # ── Header row ─────────────────────────────────────────
            hdr_row = table.rows[0]
            self._set_cell(
                hdr_row.cells[0], "Day / Period",
                bg=HEADER_COLOUR_DOCX, bold=True,
                font_colour="FFFFFF", font_size=10,
            )
            for j, period in enumerate(periods):
                self._set_cell(
                    hdr_row.cells[j + 1], str(period),
                    bg=HEADER_COLOUR_DOCX, bold=True,
                    font_colour="FFFFFF", font_size=9,
                )

            # ── Day rows ───────────────────────────────────────────
            for i, day in enumerate(days):
                row = table.rows[i + 1]
                self._set_cell(
                    row.cells[0], str(day),
                    bg=HEADER_COLOUR_DOCX, bold=True,
                    font_colour="FFFFFF", font_size=10,
                )
                for j, period in enumerate(periods):
                    cell_text = df.loc[day, period] if day in df.index and period in df.columns else ""
                    if pd.isna(cell_text):
                        cell_text = ""
                    slot_type = self._detect_type(str(cell_text))
                    colour = TYPE_COLOUR_DOCX.get(slot_type, TYPE_COLOUR_DOCX["Free"])
                    self._set_cell(
                        row.cells[j + 1], str(cell_text),
                        bg=colour, bold=False, font_size=8,
                    )

            # Set column widths (day col narrower)
            table.columns[0].width = Cm(2.5)
            for j in range(1, len(periods) + 1):
                table.columns[j].width = Cm(2.8)

            doc.add_paragraph("")  # spacing

            # Add page break after each section (except last)
            if section_id != list(section_dfs.keys())[-1]:
                doc.add_page_break()

        buf = io.BytesIO()
        doc.save(buf)
        buf.seek(0)
        logger.info(f"DOCX rendered: {len(section_dfs)} sections")
        return buf

    async def render_from_db(
        self,
        timetable_id: int,
        db: Any,
        department: str = "",
        academic_year: str = "2024-25",
    ) -> io.BytesIO:
        """Load from DB and render to DOCX."""
        from sqlalchemy import select
        from schedulo.models import TimetableSlot, Section, Timetable
        from collections import defaultdict
        from schedulo.scheduler_core.prototype_scheduler import PERIODS, DAYS

        tt_res = await db.execute(select(Timetable).where(Timetable.id == timetable_id))
        tt = tt_res.scalar_one_or_none()
        department = department or (tt.department if tt else "University")

        result = await db.execute(
            select(TimetableSlot).where(TimetableSlot.timetable_id == timetable_id)
        )
        slots = result.scalars().all()
        sec_result = await db.execute(select(Section))
        sections = {str(s.id): s.section_id for s in sec_result.scalars().all()}

        section_slots: dict[str, list] = defaultdict(list)
        for s in slots:
            section_slots[str(s.section_id or "UNK")].append(s)

        section_dfs: dict[str, pd.DataFrame] = {}
        for sec_pk, slot_list in section_slots.items():
            sec_label = sections.get(sec_pk, sec_pk)
            df = pd.DataFrame("", index=DAYS, columns=PERIODS)
            for s in slot_list:
                if s.day_name in df.index and s.period_label in df.columns:
                    parts = [s.cell_display_line1, s.cell_display_line2, s.cell_display_line3]
                    df.loc[s.day_name, s.period_label] = "\n".join(p for p in parts if p)
            section_dfs[sec_label] = df

        return self.render_from_dataframes(section_dfs, department, academic_year)

    def _set_cell(
        self,
        cell: Any,
        text: str,
        bg: str = "FFFFFF",
        bold: bool = False,
        font_colour: str = "000000",
        font_size: int = 9,
    ) -> None:
        """Style a table cell with background colour and text formatting."""
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
        from docx.shared import Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        # Background shading
        tc = cell._tc
        tcPr = tc.get_or_add_tcPr()
        shd = OxmlElement("w:shd")
        shd.set(qn("w:val"), "clear")
        shd.set(qn("w:color"), "auto")
        shd.set(qn("w:fill"), bg.upper())
        tcPr.append(shd)

        # Text
        cell.text = ""
        para = cell.paragraphs[0]
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = para.add_run(text.strip())
        run.bold = bold
        run.font.size = Pt(font_size)
        r, g, b = int(font_colour[0:2], 16), int(font_colour[2:4], 16), int(font_colour[4:6], 16)
        run.font.color.rgb = RGBColor(r, g, b)

    def _detect_type(self, text: str) -> str:
        if not text.strip():
            return "Free"
        tl = text.lower()
        if "lunch" in tl:
            return "Lunch"
        if "lab cont" in tl:
            return "Lab_Cont"
        if "(lab)" in tl or "laboratory" in tl:
            return "Lab"
        if "project" in tl:
            return "Project"
        return "Theory"
